name: Invoke-Pester

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Pester tests
        shell: pwsh
        run: Invoke-Pester -Output Detailed
